### ISSUE TITLE
Error throw on db.serialize() 

### ISSUE THREAD

**Issue by florintene** [paazmaya/image-duplicate-remover#25]
### Expected behaviour

Fresh clean install. No errors during the installation. 
When trying to compare two folders it throws an error on "db.serialize()".
Any ideas ?

### Actual behaviour
```
florin@florin-VirtualBox:/tmp/imagecompare$ image-duplicate-remover -nv ThomasLand ThomasMi/
Reading directory "/tmp/imagecompare/ThomasLand"
Reading directory "/tmp/imagecompare/ThomasMi"
Found 136 primary images to compare with 75 secondary images
/usr/local/lib/node_modules/image-duplicate-remover/index.js:150
    db.serialize(() => {
       ^

TypeError: db.serialize is not a function
    at module.exports (/usr/local/lib/node_modules/image-duplicate-remover/index.js:150:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/image-duplicate-remover/bin/image-duplicate-remover.js:126:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

### Versions and environment
 
 * Operating system: Ubuntu 18.04.1 LTS
 * Command line tool: image-duplicate-remover -nv ThomasLand ThomasMi
 * Node.js: v8.10.0
 * npm: 3.5.2
 * image-duplicate-remover: 
```
florin@florin-VirtualBox:/tmp/imagecompare$ npm list -g
/usr/local/lib
└─┬ image-duplicate-remover@0.2.1
  ├─┬ better-sqlite3@4.1.4
  │ ├── bindings@1.3.1
  │ └── integer@1.0.7
  ├─┬ chalk@2.4.1
  │ ├─┬ ansi-styles@3.2.1
  │ │ └─┬ color-convert@1.9.3
  │ │   └── color-name@1.1.3
  │ ├── escape-string-regexp@1.0.5
  │ └─┬ supports-color@5.5.0
  │   └── has-flag@3.0.0
  ├─┬ hasha@3.0.0
  │ └── is-stream@1.1.0
  ├── image-extensions@1.1.0
  ├─┬ optionator@0.8.2
  │ ├── deep-is@0.1.3
  │ ├── fast-levenshtein@2.0.6
  │ ├── levn@0.3.0
  │ ├── prelude-ls@1.1.2
  │ ├── type-check@0.3.2
  │ └── wordwrap@1.0.0
  └── readline-sync@1.4.9
```

Thank you and have some :beers:.

**Comment by paazmaya** [comment]
Thanks for the 🍻 

Looks like a bug, I will take a look

**Comment by paazmaya** [comment]
`v0.2.2` is now available, which solves this issue
