### ISSUE TITLE
SqliteError: near "?": syntax error

### ISSUE THREAD

**Issue by florintene** [paazmaya/image-duplicate-remover#26]
### Expected behaviour

Thank you for fixing the issue #25 now i'm facing a new issue. 
Now, facing a new error on running the compare: 
```(node:6481) UnhandledPromiseRejectionWarning: SqliteError: near "?": syntax error```

### Actual behaviour
Two folders "test1" and "test2" with a couple of images in them.

```
florin@florin-VirtualBox:/tmp/imagecompare$ image-duplicate-remover -nv test1/ test2/
Reading directory "/tmp/imagecompare/test1"
Reading directory "/tmp/imagecompare/test2"
Found 6 primary images to compare with 4 secondary images
Reading file: /tmp/imagecompare/test1/vid_20180930_132852_45196423144_o.jpg
Reading file: /tmp/imagecompare/test1/vid_20180930_132904_30981695627_o.jpg
Reading file: /tmp/imagecompare/test1/vid_20180930_132909_45870967552_o.jpg
Reading file: /tmp/imagecompare/test1/vid_20180930_132928_32049271848_o.jpg
Reading file: /tmp/imagecompare/test1/vid_20180930_132939_30981709217_o.jpg
Reading file: /tmp/imagecompare/test1/vid_20180930_151925_45920279211_o.jpg
Reading file: /tmp/imagecompare/test2/IMG_20180930_162514.jpg
Reading file: /tmp/imagecompare/test2/IMG_20180930_162545.jpg
Reading file: /tmp/imagecompare/test2/IMG_20180930_162659.jpg
Reading file: /tmp/imagecompare/test2/IMG_20180930_162705.jpg
(node:6481) UnhandledPromiseRejectionWarning: SqliteError: near "?": syntax error
    at Promise (/usr/local/lib/node_modules/image-duplicate-remover/lib/find-matching.js:56:22)
    at new Promise (<anonymous>)
    at queryDatabase (/usr/local/lib/node_modules/image-duplicate-remover/lib/find-matching.js:47:10)
    at primaryImages.map (/usr/local/lib/node_modules/image-duplicate-remover/lib/find-matching.js:101:12)
    at Array.map (<anonymous>)
    at findMatching (/usr/local/lib/node_modules/image-duplicate-remover/lib/find-matching.js:100:34)
    at module.exports (/usr/local/lib/node_modules/image-duplicate-remover/index.js:154:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/image-duplicate-remover/bin/image-duplicate-remover.js:126:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
(node:6481) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:6481) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Versions and environment

 * Operating system: Ubuntu 18.04.1 LTS
 * Command line tool: image-duplicate-remover -nv test1/ test2/
 * Node.js: v8.10.0
 * npm: 3.5.2
 * image-duplicate-remover:

```
florin@florin-VirtualBox:/tmp/imagecompare$ npm list -g
/usr/local/lib
└─┬ image-duplicate-remover@0.2.1
  ├─┬ better-sqlite3@4.1.4
  │ ├── bindings@1.3.1
  │ └── integer@1.0.7
  ├─┬ chalk@2.4.1
  │ ├─┬ ansi-styles@3.2.1
  │ │ └─┬ color-convert@1.9.3
  │ │   └── color-name@1.1.3
  │ ├── escape-string-regexp@1.0.5
  │ └─┬ supports-color@5.5.0
  │   └── has-flag@3.0.0
  ├─┬ hasha@3.0.0
  │ └── is-stream@1.1.0
  ├── image-extensions@1.1.0
  ├─┬ optionator@0.8.2
  │ ├── deep-is@0.1.3
  │ ├── fast-levenshtein@2.0.6
  │ ├── levn@0.3.0
  │ ├── prelude-ls@1.1.2
  │ ├── type-check@0.3.2
  │ └── wordwrap@1.0.0
  └── readline-sync@1.4.9
```

Thank you and have some more :beers:. :)

**Comment by paazmaya** [comment]
`v0.2.2` is now available, which solves this issue
